### ISSUE TITLE
FIX MY STUFF

### ISSUE THREAD

**Issue by GregWirth** [dayne/qgis-cookbook#1]
HOW DO FIX!

**Comment by dayne** [comment]
Ahh yes - the packages cannot be authenticated issue we saw.

```
WARNING: The following packages cannot be authenticated!
             qgis-providers-common libqgis-core2.10.1 libqgis-gui2.10.1 qgis-providers
             libqgis-analysis2.10.1 libqgis-customwidgets libqgis-networkanalysis2.10.1
             libqgis-server2.10.1 libqgisgrass2.10.1 libqgispython2.10.1
             python-qgis-common python-qgis qgis-common qgis qgis-plugin-globe-common
             qgis-plugin-globe qgis-plugin-grass-common qgis-plugin-grass
           STDERR: E: There are problems and -y was used without --force-yes
           ---- End output of apt-get -q -y install qgis=1:2.10.1+20trusty-ubuntugis ----
           Ran apt-get -q -y install qgis=1:2.10.1+20trusty-ubuntugis returned 100
```

Found the issue - turns out qgis.org's key expires this month and so for 2.10 they are signing with their new key:  D71472C4

http://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

Running test now for the updated key. If the converge is successful I'll push the update and have you upgrade the qgis cookbook for GINA.

I'm not sure how well this will roll out to existing systems with gis_workstation - I am guessing we'll need to do a manual `apt-get update && apt-get upgrade` to have this applied so they too get Qgis 2.10.
